spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "${DB_USERNAME}"
            client-secret: "${DB_PASSWORD}"
  application:
    name:
      parking-guru
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
app:
  jwt:
    secret: value
    expiration:
      minutes: 10