spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "${clientId}"
            client-secret: "${clientSecret}"
  application:
    name:
      parking-guru
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
app:
  jwt:
    secret: owilkajsvkljasjklaenvjlrejvrankojvavnkjfewnvjklrsernvlkjwenin34ij89fnewnp9v43n
    expiration:
      minutes: 10